# Generated by Django 2.2.12 on 2023-02-21 11:53

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='q3',
            field=otree.db.models.StringField(choices=[['0', 'Scuola elementare/media'], ['1', 'Diploma scuola superiore'], ['2', 'Laurea 3 anni'], ['3', 'Laurea 5 anni'], ['4', 'Master'], ['5', 'Dottorato']], max_length=10000, null=True, verbose_name='3. Titolo di studio'),
        ),
    ]
