# Generated by Django 2.2.12 on 2023-02-21 12:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase4', '0002_auto_20230221_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q13_f',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q14_f',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='q15_f',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
