# Generated by Django 2.2.12 on 2023-02-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fase4', '0003_auto_20230221_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='q12_1',
        ),
    ]
