# Generated by Django 2.2.12 on 2023-02-11 15:17

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase4', '0004_auto_20230211_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='qred1',
            field=otree.db.models.IntegerField(null=True, verbose_name='Quale è stato il suo reddito ad ettaro da mele nel 2020 '),
        ),
        migrations.AddField(
            model_name='player',
            name='qred2',
            field=otree.db.models.IntegerField(null=True, verbose_name='Quale è stato il suo reddito ad ettaro da mele nel 2021 '),
        ),
        migrations.AddField(
            model_name='player',
            name='qred3',
            field=otree.db.models.IntegerField(null=True, verbose_name='Quale è stato il suo reddito ad ettaro da mele nel 2022 '),
        ),
    ]
