# Generated by Django 2.2.12 on 2023-02-22 11:26

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase4', '0004_remove_player_q12_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='q16_l',
            field=otree.db.models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
