# Generated by Django 2.2.12 on 2023-02-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fase4', '0005_player_q16_l'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='q7_a4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_a5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_b4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_b5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_c4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_c5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_d4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_d5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_e4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_e5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_f4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q7_f5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_a4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_a5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_b4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_b5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_c4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_c5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_d4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_d5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_e4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_e5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_f4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q8_f5',
        ),
    ]
