# Generated by Django 2.2.12 on 2023-01-31 13:00

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1_SuperLite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=otree.db.models.StringField(max_length=10000, null=True, verbose_name='Il vostro nome e cognome:'),
        ),
    ]
