# Generated by Django 2.2.12 on 2023-02-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fase_Likert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='q_loss7',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q_time1',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q_time2',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q_time3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q_time4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q_time5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q_time6',
        ),
        migrations.RemoveField(
            model_name='player',
            name='q_time7',
        ),
    ]
