# Generated by Django 2.2.12 on 2023-02-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fase_Likert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='q_loss1',
        ),
    ]
