# Generated by Django 2.2.12 on 2023-02-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fase_Likert', '0002_remove_player_q_loss1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='q_loss5',
        ),
    ]
