# Generated by Django 2.2.12 on 2023-01-27 23:13

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fase1_lite_group', to='otree.Session')),
            ],
            options={
                'db_table': 'Fase1_Lite_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fase1_lite_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'Fase1_Lite_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('quizf1', otree.db.models.StringField(choices=[['2', '4.39 €'], ['2', '5.69 €'], ['1', '7.79 €']], default='', max_length=10000, null=True, verbose_name='1. In base alla figura mostrata quale sarà il suo guadagno se il reddito varierà tra +1% e +10%?')),
                ('quiz2f1', otree.db.models.StringField(choices=[['2', '3.39 €'], ['2', '5.69 €'], ['1', '7.79 €']], default='', max_length=10000, null=True, verbose_name='1. In base alla figura mostrata quale sarà il suo guadagno se il reddito varierà tra +1% e +10%?')),
                ('labelset', otree.db.models.IntegerField(default=0, null=True)),
                ('final_payment', otree.db.models.StringField(max_length=10000, null=True)),
                ('bin1', otree.db.models.IntegerField(default=0, null=True)),
                ('bin2', otree.db.models.IntegerField(default=0, null=True)),
                ('bin3', otree.db.models.IntegerField(default=0, null=True)),
                ('bin4', otree.db.models.IntegerField(default=0, null=True)),
                ('bin5', otree.db.models.IntegerField(default=0, null=True)),
                ('bin6', otree.db.models.IntegerField(default=0, null=True)),
                ('bin7', otree.db.models.IntegerField(default=0, null=True)),
                ('bin8', otree.db.models.IntegerField(default=0, null=True)),
                ('bin9', otree.db.models.IntegerField(default=0, null=True)),
                ('bin10', otree.db.models.IntegerField(default=0, null=True)),
                ('rip1', otree.db.models.StringField(choices=[['0', 'Penso che questa allocazione rispecchi accuratamente la mia opinione, non voglio procedere con altre allocazioni'], ['1', 'Voglio procedere con una seconda allocazione']], default='', max_length=10000, null=True, verbose_name='')),
                ('rip2', otree.db.models.StringField(choices=[['0', 'Penso che questa allocazione rispecchi accuratamente la mia opinione, non voglio procedere con altre allocazioni'], ['1', 'Voglio procedere con una terza allocazione']], default='', max_length=10000, null=True, verbose_name='')),
                ('pref1', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=6, null=True, verbose_name='')),
                ('pref2', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=6, null=True, verbose_name='')),
                ('pref3', otree.db.models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=6, null=True, verbose_name='')),
                ('sum_token', otree.db.models.FloatField(default=18, null=True)),
                ('w_amt', otree.db.models.FloatField(default=0, null=True, verbose_name='')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fase1_Lite.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fase1_lite_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fase1_lite_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fase1_Lite.Subsession')),
            ],
            options={
                'db_table': 'Fase1_Lite_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fase1_Lite.Subsession'),
        ),
    ]
