# Generated by Django 2.2.12 on 2023-02-11 15:47

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Fase1_Lite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avginc',
            field=otree.db.models.FloatField(default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='income1',
            field=otree.db.models.FloatField(default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='income2',
            field=otree.db.models.FloatField(default=0, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='player',
            name='income3',
            field=otree.db.models.FloatField(default=0, null=True, verbose_name=''),
        ),
    ]
